/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
	aws_project_region: "us-east-1",
	aws_cognito_identity_pool_id:
		"us-east-1:43b0c8cd-fa2f-4df6-9c05-d691279c53f6",
	aws_cognito_region: "us-east-1",
	aws_user_pools_id: "us-east-1_KlLAMMzjF",
	aws_user_pools_web_client_id: "5on241l9tpilsa9mmblco45chh",
	oauth: {},
	aws_cognito_username_attributes: [],
	aws_cognito_social_providers: [],
	aws_cognito_signup_attributes: ["EMAIL"],
	aws_cognito_mfa_configuration: "OFF",
	aws_cognito_mfa_types: ["SMS"],
	aws_cognito_password_protection_settings: {
		passwordPolicyMinLength: 8,
		passwordPolicyCharacters: [],
	},
	aws_cognito_verification_mechanisms: ["EMAIL"],
	Auth: {
		region: "us-east-1",
		userPoolId: "us-east-1_KlLAMMzjF",
		userPoolWebClientId: "5on241l9tpilsa9mmblco45chh",
		identityPoolId: "us-east-1:43b0c8cd-fa2f-4df6-9c05-d691279c53f6",
		mandatorySignIn: true,
	},
	API: {
		endpoints: [
			{
				name: "UserProfileAPI",
				endpoint: "https://56mg9qlyf3.execute-api.us-east-1.amazonaws.com/prod",
			},
		],
	},
};

export default awsmobile;
