/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
	aws_project_region: "us-east-1",
	aws_cognito_identity_pool_id:
		"us-east-1:1c843e86-e72d-49f0-a909-dbcd84bb2691",
	aws_cognito_region: "us-east-1",
	aws_user_pools_id: "us-east-1_eG5WTl36x",
	aws_user_pools_web_client_id: "ap35s0lgkee3gcu93jog9s0tg",
	oauth: {},
	aws_cognito_username_attributes: [],
	aws_cognito_social_providers: [],
	aws_cognito_signup_attributes: ["EMAIL"],
	aws_cognito_mfa_configuration: "OFF",
	aws_cognito_mfa_types: ["SMS"],
	aws_cognito_password_protection_settings: {
		passwordPolicyMinLength: 8,
		passwordPolicyCharacters: [],
	},
	aws_cognito_verification_mechanisms: ["EMAIL"],
	Auth: {
		region: "us-east-1",
		userPoolId: "us-east-1_eG5WTl36x",
		userPoolWebClientId: "ap35s0lgkee3gcu93jog9s0tg",
		identityPoolId: "us-east-1:1c843e86-e72d-49f0-a909-dbcd84bb2691",
		mandatorySignIn: true,
	},
	API: {
		endpoints: [
			{
				name: "UserProfileAPI",
				endpoint: "https://56mg9qlyf3.execute-api.us-east-1.amazonaws.com/prod",
			},
		],
	},
};

export default awsmobile;
